name = "SizedStrings"
uuid = "f469014f-b01a-4cc4-831a-c5604b331f4f"
authors = ["Jeff Bezanson <jeff.bezanson@gmail.com>", "Paul Nemec <paul.nemec@tum.de>"]
version = "0.0.1"

[compat]
julia = "0.7 - 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
